version: '3.3'

services:
  mysql_db:
      image: mysql:8.0
      restart: unless-stopped
      container_name: mysql_db
      environment:
        MYSQL_DATABASE: books
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: test
        MYSQL_PASSWORD: test
      volumes:
        - ./sql:/docker-entrypoint-initdb.d
      # expose:
      #   - 3306



  node_fe:
    depends_on:
      - mysql_db
    build: .
    ports:
      - "3000:8000"
    restart: unless-stopped
    container_name: node_fe
    # links:
    #   - mysql_db:mysql_db


volumes: 
  db: